let str1 = "String1";
let str2 = "String2";
console.log(str1.concat(str2));
console.log(str1.toLowerCase());
console.log(str1.toUpperCase());
console.log(str1.length);
console.log(str1.charAt(1));
console.log(str1.startsWith("St"));
console.log(str1.endsWith("1"));
let charArray = str1.split('');
console.log(charArray);
console.log(charArray.toString());
console.log(charArray.toString().replaceAll(',', ''));
console.log(str1.replace('i', 'k'));
console.log(str1 === str2);
console.log(str1.indexOf('1'));
console.log(str1.lastIndexOf('g'));
console.log(str1.substring(2));
console.log(str1.substring(3, 6));